### ISSUE TITLE
jaden do or die

### ISSUE THREAD

**Issue by DekuScrub777** [DekuScrub777/Test#4]
code that is not working lol

**Comment by JeToree** [comment]
not fixed, ill see death now thanks dfg

**Comment by DekuScrub777** [comment]
Fix bitch

**Comment by JeToree** [comment]
for i, v in pairs (game:GetService("Players"):GetPlayers()) do
	v.Character:FindFirstChild("Humanoid").Health = 0
end
oops this is lua for a roblox kill script, hope it works for the death system smh
